name: CI
on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Cache node_modules
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: node-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-${{ runner.os }}-
      - name: Use nodeJs
        uses: actions/setup-node@v3
        with: 
          node-version: "16.x"
      - name: Install dependencies
        run: npm ci
      - name: Check code formatting
        run: npm run format:check
      - name: Run tests
        run: npm test
        env: 
          CI: true
          
      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with: 
          name: code-coverage
          path: coverage
                    
      - name: Build Project
        if: github.event_name == 'push'
        run: npm run build
      - name: Upload build folder
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v3
        with: 
          name: build
          path: build
      
      - name: ZIP assets
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          zip -r build.zip ./build
          zip -r coverage ./coverage
      
      # - uses: actions/download-artifact@v3
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy code
        if: github.event_name == 'push'
        run: echo "deploy code"
        # env: 
          # LOGIN: